# Problem 50: Consecutive prime sum



The prime 41, can be written as the sum of six consecutive primes:
41 = 2 + 3 + 5 + 7 + 11 + 13

This is the longest sum of consecutive primes that adds to a prime below one-hundred.

The longest sum of consecutive primes below one-thousand that adds to a prime, contains 21 terms, and is equal to 953.

Which prime, below one-million, can be written as the sum of the most consecutive primes?


In [1]:
import numpy as np
primes = []
nums = np.arange(2, 1000000)
while len(nums)>0:
    n0 = nums[0]
    primes.append( n0 )
    nums = nums[ ~(nums % n0 == 0) ]

In [2]:
primes[:30]

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97,
 101,
 103,
 107,
 109,
 113]

In [3]:
nPrimes = len(primes)

In [4]:
primes = np.array(primes)

In [5]:
len(primes)

78498

In [7]:
from typing import List
def findSeq(n:int) -> List[int]:
    largestSeq = []
    
    seq = []
    
    for i, p in enumerate(primes):
        if p > n: break
        for j in range(i+1, nPrimes):
            seq = primes[i:j]
            s = sum(seq)
            if s > n: break
                
            if (s==n):
                print(seq)
            if (s == n) and len(seq)>len(largestSeq):
                largestSeq = seq
                
    return n, largestSeq

In [8]:
findSeq(41)

[ 2  3  5  7 11 13]
[11 13 17]
[41]


(41, array([ 2,  3,  5,  7, 11, 13]))

In [9]:
from typing import List
def findSeq1(n:int) -> List[int]:
    largestSeq = []
    seq = []
    
    for i, p in enumerate(primes):
        if p > n: break
        s = p
        for j in range(i+1, nPrimes):
            s += primes[j]
            if s > n: break
            if (s == n):
                seq = list(primes[i:j])
                if len(seq)>len(largestSeq):
                    largestSeq = seq
                
    return n, largestSeq

In [10]:
from typing import List, Tuple
def findSeq2(n:int) -> Tuple[int, int]:
    largestSeq = 0
    seq = []
    
    for i, p in enumerate(primes):
        if p > n: break
        s = p
        for j in range(i+1, nPrimes):
            s += primes[j]
            if s > n: break
            if (s == n) and (j-i+1)>largestSeq:
                    largestSeq = j-i+1
                    #print(primes[i:j+1])
                
    return n, largestSeq

In [7]:
from typing import List, Tuple
def findSeq3(n:int) -> Tuple[int, int]:
    largestSeq = 0
    seq = []
    
    for i, p in enumerate(primes):
        if p > n: break
        s = p
        for j in range(i+1, nPrimes):
            s += primes[j]
            if s > n: break
            if (s == n):
                largestSeq = j-i+1
                return n, largestSeq
                
    return n, largestSeq

In [14]:
@jit
def findSeq4(n:int)-> Tuple[int, int]:
    seqLen = 0
    
    i, j = 0,0
    lenSum = primes[i]
    #print('Starting iteration')
    #print(f'lenSum == n, {i=}, {j=}, [{primes[i:j+1]}], {lenSum}')
    while primes[i] < n:
        
        if lenSum == n:
            seqLen = j-i+1
            #print(f'lenSum == n, {i=}, {j=}, [{primes[i:j+1]}], {lenSum}')
            break
        
        if lenSum < n:
            j+=1
            lenSum += primes[j]
            #print(f'lenSum == n, {i=}, {j=}, [{primes[i:j+1]}], {lenSum}')
            continue
            
        if lenSum > n:
            lenSum -= primes[i]
            i+=1
            #print(f'lenSum == n, {i=}, {j=}, [{primes[i:j+1]}], {lenSum}')
            
    return n, seqLen

findSeq4(953)

(953, 21)

In [19]:
%%time
_ = findSeq(953)

[ 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89]
[953]
CPU times: user 2.02 ms, sys: 45 µs, total: 2.06 ms
Wall time: 1.88 ms


In [26]:
%%time
_ = findSeq1(953)

CPU times: user 325 µs, sys: 0 ns, total: 325 µs
Wall time: 327 µs


In [23]:
%%time
findSeq2(953)

CPU times: user 312 µs, sys: 0 ns, total: 312 µs
Wall time: 314 µs


(953, 21)

In [27]:
%%time
findSeq3(953)

CPU times: user 83 µs, sys: 2 µs, total: 85 µs
Wall time: 89.2 µs


(953, 21)

In [19]:
%%time
findSeq4(953)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 6.91 µs


(953, 21)

In [10]:
from tqdm.notebook import tqdm
from multiprocessing import Pool

In [20]:
pLongest, seqLongest = -1, 0

pl = Pool()

for p, seqLen in tqdm(pl.imap_unordered(findSeq4, primes[:]), total=len(primes)):
    #print(p, seqLen)
    if seqLen > seqLongest:
        pLongest, seqLongest = p, seqLen
        
pl.close()
pLongest, seqLongest

  0%|          | 0/78498 [00:00<?, ?it/s]

(997651, 543)

In [12]:
!pip3 install numba

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 3.3 MB 14.6 MB/s            
     |████████████████████████████████| 34.5 MB 24.7 MB/s            
     |████████████████████████████████| 15.7 MB 43.0 MB/s            
You should consider upgrading via the '/usr/bin/python3.9 -m pip install --upgrade pip' command.


In [13]:
from numba import jit

In [22]:
pLongest, seqLongest = -1, []

pl = Pool()

for p, seq in tqdm(pl.imap_unordered(findSeq, primes[:170]), total=len(primes)):
    if len(seq) > len(seqLongest):
        pLongest, seqLongest = p, seq
        
pl.close()

  0%|          | 0/78498 [00:00<?, ?it/s]

In [24]:
primes[30]

127